bug fixes, regex
Line 721:Corrected regex to include additional characters among which "-" broken by #72.
Line 742: Corrected regex to include additional characters and unified with Line 721 regex. I believe the inclusion of '"' here was alternative root cause of #82 but it has now been fixed elsewhere.
Line 791: Corrected use of "has_key" which threw an error: "AttributeError: 'dict' object has no attribute 'has_key'".  ('has_key' was removed in Python 3)